workflows:
  build-and-deploy:
    name: Build and Deploy
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          xcodebuild -workspace MovieHub.xcworkspace -scheme MovieHub -configuration Release -archivePath $HOME/build/MovieHub.xcarchive archive
          xcodebuild -exportArchive -archivePath $HOME/build/MovieHub.xcarchive -exportPath $HOME/build/MovieHub.ipa -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/MovieHub.ipa
    publishing:
      email:
        recipients:
          - egifcb@gmail.com
