workflows:
  build-and-deploy:
    name: Build and Deploy
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          xcodebuild -workspace MyApp.xcworkspace -scheme MyApp -configuration Release -archivePath $HOME/build/MyApp.xcarchive archive
          xcodebuild -exportArchive -archivePath $HOME/build/MyApp.xcarchive -exportPath $HOME/build/MyApp.ipa -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/MyApp.ipa
    publishing:
      email:
        recipients:
          - egifcb@gmail.com
