workflows:
  build-and-deploy:
    name: Build and Deploy
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_PROJECT: "MovieHub.xcodeproj" # Isikan nama project Anda.
          XCODE_SCHEME: "MovieHub" # Isikan nama scheme project Anda.
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - egifcb@gmail.com
