workflows:
  build-and-deploy:
    name: Build and Deploy
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com
        subject: Your app is ready!
        body: |
          Your app has been successfully built and deployed to CodeMagic.
          You can download the IPA file from the following link: $LINK
